qterminal (0.6.0-1~20141027+1)
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/qterminal/debian/jessie/debian/prerm b/qterminal/debian/jessie/debian/prerm
--- a/qterminal/debian/jessie/debian/prerm
+++ b/qterminal/debian/jessie/debian/prerm
@@ -1,22 +1,33 @@
 #!/bin/sh
-# prerm script for qterminal
+# postrm script for qterminal
 #
 # see: dh_installdeb(1)
 
 set -e
 
-case "$1" in
-    remove|upgrade|deconfigure)
-    update-alternatives --remove x-terminal-emulator /usr/bin/qterminal
-    ;;
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-    failed-upgrade)
-    ;;
+
+case "$1" in
+    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+        update-alternatives --remove x-terminal-emulator /usr/bin/qterminal 
+        ;;
 
     *)
-        echo "prerm called with unknown argument \`$1'" >&2
+        echo "postrm called with unknown argument \`$1'" >&2
         exit 1
-    ;;
+        ;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
@@ -25,5 +36,3 @@ esac
 #DEBHELPER#
 
 exit 0
-
-
