bb-wl18xx-firmware (1.20221130.2)
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/bb-wl18xx-firmware/suite/focal/debian/bb-wl18xx-select-fw b/bb-wl18xx-firmware/suite/focal/debian/bb-wl18xx-select-fw
--- a/bb-wl18xx-firmware/suite/focal/debian/bb-wl18xx-select-fw
+++ b/bb-wl18xx-firmware/suite/focal/debian/bb-wl18xx-select-fw
@@ -34,6 +34,11 @@ else
 		rm -rf /lib/firmware/ti-connectivity/wl18xx-fw-4.bin
 		cp -v /lib/firmware/ti-connectivity/git/wl18xx-fw-4-${FW_OPTION}.bin /lib/firmware/ti-connectivity/wl18xx-fw-4.bin
 		sync
-		update-initramfs -u
+		#Some users dont run with an initrd.img
+		if [ -f /boot/initrd.img-`uname -r`] ; then
+			update-initramfs -u || true
+		fi
+	else
+		echo "Unable to find /lib/firmware/ti-connectivity/git/wl18xx-fw-4-${FW_OPTION}.bin"
 	fi
 fi
