seeed-wificonfig-installer (0.1.0-0rcnee7~bpo80+20160512+1)
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/seeed-wificonfig-installer/suite/jessie/debian/prerm b/seeed-wificonfig-installer/suite/jessie/debian/prerm
--- a/seeed-wificonfig-installer/suite/jessie/debian/prerm
+++ b/seeed-wificonfig-installer/suite/jessie/debian/prerm
@@ -16,6 +16,53 @@ if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
 	systemctl stop wificonfig.service || true
 fi
 
+package="seeed-wificonfig-installer"
+
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+remove_file () {
+	if [ -f /var/cache/${package}/${wfile} ] ; then
+		rm -f /var/cache/${package}/${wfile}
+	fi
+}
+
+remove_dir () {
+	if [ -d ${wdir} ] ; then
+		rm -rf ${wdir}
+	fi
+}
+
+remove_all() {
+	wdir="/usr/local/lib/node_modules/wificonfig/" ; remove_dir
+	#wfile="wificonfig-0.1.0-e4e30e7-v0.12.13.tar.xz" ; remove_file
+
+	#Always keep the current one for quick reinstalls...
+	#wfile="wificonfig-0.1.0-e4e30e7-v0.12.13.tar.xz" ; remove_file
+}
+
+case "$1" in
+    remove|upgrade|deconfigure)
+	remove_all
+    ;;
+
+    failed-upgrade)
+    ;;
+
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
