seeed-wificonfig-installer (0.0.6-0rcnee6~bpo80+20160503+1)
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/seeed-wificonfig-installer/suite/jessie/debian/wifidog_pre b/seeed-wificonfig-installer/suite/jessie/debian/wifidog_pre
--- a/seeed-wificonfig-installer/suite/jessie/debian/wifidog_pre
+++ b/seeed-wificonfig-installer/suite/jessie/debian/wifidog_pre
@@ -1,26 +1,29 @@
 #!/bin/bash -e
 
-iw dev SoftAp0 del &> /dev/null || true
+if [ ! -f /tmp/wifi.up ] ; then
+	iw dev SoftAp0 del &> /dev/null || true
 
-iw phy phy0 interface add SoftAp0 type managed
+	iw phy phy0 interface add SoftAp0 type managed
 
-p=$?
-if [ $p==0 ];then
-	echo "phy0 created "
-else
-	echo "Err: can't creat phy0 "
-	exit 1
+	p=$?
+	if [ $p==0 ];then
+		echo "phy0 created "
+	else
+		echo "Err: can't creat phy0 "
+		exit 1
+	fi
+
+	ip link set dev SoftAp0 down
+	ip link set dev SoftAp0 address 02:03:04:05:06:07
+	ip link set dev SoftAp0 up
+	ip addr add 192.168.8.1/24 broadcast 192.168.8.255 dev SoftAp0
+
+	echo 1 > /proc/sys/net/ipv4/ip_forward
+	iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
+	iptables -A FORWARD -i wlan0 -o SoftAp0 -m state --state RELATED,ESTABLISHED -j ACCEPT
+	iptables -A FORWARD -i SoftAp0 -o wlan0 -j ACCEPT
+	touch /tmp/wifi.up
 fi
-
-ip link set dev SoftAp0 down
-ip link set dev SoftAp0 address 02:03:04:05:06:07
-ip link set dev SoftAp0 up
-ip addr add 192.168.8.1/24 broadcast 192.168.8.255 dev SoftAp0
-
-echo 1 > /proc/sys/net/ipv4/ip_forward
-iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
-iptables -A FORWARD -i wlan0 -o SoftAp0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-iptables -A FORWARD -i SoftAp0 -o wlan0 -j ACCEPT
 
 /usr/bin/wifidog -f -d 7
 #systemctl start wificonfig.service || true
