doc-beaglebone-getting-started (1.20170526-0rcnee0)
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/bb-doc-beaglebone-getting-started/suite/bionic/debian/prerm b/bb-doc-beaglebone-getting-started/suite/bionic/debian/prerm
--- a/bb-doc-beaglebone-getting-started/suite/bionic/debian/prerm
+++ b/bb-doc-beaglebone-getting-started/suite/bionic/debian/prerm
@@ -5,35 +5,17 @@
 set -e
 
 package="doc-beaglebone-getting-started"
-core_version="2017-05-25"
-file_type="img"
-#file_type="iso"
-wfile="beaglebone-getting-started-${core_version}.${file_type}"
-wfile_xz="beaglebone-getting-started-${core_version}.${file_type}.xz"
 
 # summary of how this script can be called:
-#        * <postinst> `configure' <most-recently-configured-version>
-#        * <old-postinst> `abort-upgrade' <new version>
-#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
-#          <new-version>
-#        * <postinst> `abort-remove'
-#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
-#          <failed-install-package> <version> `removing'
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
 #          <conflicting-package> <version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
-
-just_install () {
-	cd /var/cache/${package}/
-
-	if [ ! -f ${wfile} ] ; then
-		unxz ${wfile_xz}
-	fi
-
-	if [ -f ${wfile} ] ; then
-		ln -sf /var/cache/${package}/beaglebone-getting-started-${core_version}.${file_type} /var/local/bb_usb_mass_storage.${file_type}
-	fi
-}
 
 remove_file () {
 	if [ -f /var/cache/${package}/${wfile} ] ; then
@@ -57,22 +39,23 @@ remove_all() {
 	wfile="beaglebone-getting-started-2017-01-25.img.xz" ; remove_file
 	wfile="beaglebone-getting-started-2017-01-25.img" ; remove_file
 	wfile="beaglebone-getting-started-2017-05-25.img.xz" ; remove_file
+	wfile="beaglebone-getting-started-2017-05-25.img" ; remove_file
+	wfile="beaglebone-getting-started-2017-05-26.img.xz" ; remove_file
 
 	#Always keep the current one for quick reinstalls...
-	#wfile="beaglebone-getting-started-2017-05-25.img" ; remove_file
+	#wfile="beaglebone-getting-started-2017-05-26.img" ; remove_file
 }
 
 case "$1" in
-    configure)
-	just_install
+    remove|upgrade|deconfigure)
 	remove_all
     ;;
 
-    abort-upgrade|abort-remove|abort-deconfigure)
+    failed-upgrade)
     ;;
 
     *)
-        echo "postinst called with unknown argument \`$1'" >&2
+        echo "prerm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
@@ -83,4 +66,3 @@ esac
 #DEBHELPER#
 
 exit 0
-
