bb-usb-gadgets (1.20210816.0)
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/bb-usb-gadgets/suite/bullseye/debian/bb-start-usb-gadgets b/bb-usb-gadgets/suite/bullseye/debian/bb-start-usb-gadgets
--- a/bb-usb-gadgets/suite/bullseye/debian/bb-start-usb-gadgets
+++ b/bb-usb-gadgets/suite/bullseye/debian/bb-start-usb-gadgets
@@ -8,15 +8,20 @@ run_libcomposite () {
 }
 
 use_libcomposite () {
-	echo "${log} modprobe libcomposite"
-	modprobe libcomposite || true
-	if [ -d /sys/module/libcomposite ] ; then
+	echo "${log} Looking for libcomposite module"
+	if [ -d /sys/kernel/config/usb_gadget/ ] ; then
 		run_libcomposite
 	else
-		if [ -f /sbin/depmod ] ; then
-			/sbin/depmod -a
+		echo "${log} modprobe libcomposite"
+		modprobe libcomposite || true
+		if [ -d /sys/module/libcomposite ] ; then
+			run_libcomposite
+		else
+			if [ -f /sbin/depmod ] ; then
+				/sbin/depmod -a
+			fi
+			echo "${log} ERROR: [libcomposite didn't load]"
 		fi
-		echo "${log} ERROR: [libcomposite didn't load]"
 	fi
 }
 
